import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.highgui.HighGui;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.imgproc.LineSegmentDetector;

/**
* GripPipelineLinesFromTarget class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/
public class GripPipelineLinesFromTarget {

	public static class OuterPortTargetInImage {
		double widthPx;
		double xPx, yPx;
	}
	public static class OuterPortTargetRelRobot {
		/** Horizontal in */
		double rangeInches;
		/** Degrees in azimuth relative to camera boresight. Positive is to the left, negative is to the right. */
		double bearingDegrees;
	}

	//Outputs
	private Mat blurOutput = new Mat();
	private Mat hsvThresholdOutput = new Mat();
	private ArrayList<Line> findLinesOutput = new ArrayList<Line>();
	private ArrayList<Line> filterLinesOutput = new ArrayList<Line>();
	private OuterPortTargetInImage detectedTargetInImage = null;
	private OuterPortTargetRelRobot detectedTargetRelRobot = null;

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	public void process(Mat source0) {
		// Step Blur0:
		Mat blurInput = source0;
		BlurType blurType = BlurType.get("Box Blur");
		double blurRadius = 2.7027027027027026;
		blur(blurInput, blurType, blurRadius, blurOutput);

		// Step HSV_Threshold0:
		Mat hsvThresholdInput = blurOutput;
		double[] hsvThresholdHue = {45.69817278554671, 86.42413746834596};
		double[] hsvThresholdSaturation = {160.52158273381295, 255.0};
		double[] hsvThresholdValue = {75.67446043165472, 255.0};
		hsvThreshold(hsvThresholdInput, hsvThresholdHue, hsvThresholdSaturation, hsvThresholdValue, hsvThresholdOutput);

		// Step Find_Lines0:
		Mat findLinesInput = hsvThresholdOutput;
		findLines(findLinesInput, findLinesOutput);

		// Step Filter_Lines0:
		ArrayList<Line> filterLinesLines = findLinesOutput;
		double filterLinesMinLength = 10.0;
		double[] filterLinesAngle = {0, 360};
		filterLines(filterLinesLines, filterLinesMinLength, filterLinesAngle, filterLinesOutput);

		// Find targets
		detectedTargetInImage = findTarget(filterLinesOutput);

		// Compute where the target lies relative to the robot
		// TODO
	}

	/**
	 * This method is a generated getter for the output of a Blur.
	 * @return Mat output from Blur.
	 */
	public Mat blurOutput() {
		return blurOutput;
	}

	/**
	 * This method is a generated getter for the output of a HSV_Threshold.
	 * @return Mat output from HSV_Threshold.
	 */
	public Mat hsvThresholdOutput() {
		return hsvThresholdOutput;
	}

	/**
	 * This method is a generated getter for the output of a Find_Lines.
	 * @return ArrayList<Line> output from Find_Lines.
	 */
	public ArrayList<Line> findLinesOutput() {
		return findLinesOutput;
	}

	/**
	 * This method is a generated getter for the output of a Filter_Lines.
	 * @return ArrayList<Line> output from Filter_Lines.
	 */
	public ArrayList<Line> filterLinesOutput() {
		return filterLinesOutput;
	}


	/**
	 * An indication of which type of filter to use for a blur.
	 * Choices are BOX, GAUSSIAN, MEDIAN, and BILATERAL
	 */
	enum BlurType{
		BOX("Box Blur"), GAUSSIAN("Gaussian Blur"), MEDIAN("Median Filter"),
			BILATERAL("Bilateral Filter");

		private final String label;

		BlurType(String label) {
			this.label = label;
		}

		public static BlurType get(String type) {
			if (BILATERAL.label.equals(type)) {
				return BILATERAL;
			}
			else if (GAUSSIAN.label.equals(type)) {
			return GAUSSIAN;
			}
			else if (MEDIAN.label.equals(type)) {
				return MEDIAN;
			}
			else {
				return BOX;
			}
		}

		@Override
		public String toString() {
			return this.label;
		}
	}

	/**
	 * Softens an image using one of several filters.
	 * @param input The image on which to perform the blur.
	 * @param type The blurType to perform.
	 * @param doubleRadius The radius for the blur.
	 * @param output The image in which to store the output.
	 */
	private static void blur(Mat input, BlurType type, double doubleRadius,
		Mat output) {
		int radius = (int)(doubleRadius + 0.5);
		int kernelSize;
		switch(type){
			case BOX:
				kernelSize = 2 * radius + 1;
				Imgproc.blur(input, output, new Size(kernelSize, kernelSize));
				break;
			case GAUSSIAN:
				kernelSize = 6 * radius + 1;
				Imgproc.GaussianBlur(input,output, new Size(kernelSize, kernelSize), radius);
				break;
			case MEDIAN:
				kernelSize = 2 * radius + 1;
				Imgproc.medianBlur(input, output, kernelSize);
				break;
			case BILATERAL:
				Imgproc.bilateralFilter(input, output, -1, radius, radius);
				break;
		}
	}

	/**
	 * Segment an image based on hue, saturation, and value ranges.
	 *
	 * @param input The image on which to perform the HSL threshold.
	 * @param hue The min and max hue
	 * @param sat The min and max saturation
	 * @param val The min and max value
	 * @param output The image in which to store the output.
	 */
	private void hsvThreshold(Mat input, double[] hue, double[] sat, double[] val,
	    Mat out) {
		Imgproc.cvtColor(input, out, Imgproc.COLOR_BGR2HSV);
		Core.inRange(out, new Scalar(hue[0], sat[0], val[0]),
			new Scalar(hue[1], sat[1], val[1]), out);
	}

	public static class Line {
		public final double x1, y1, x2, y2;
		public Line(double x1, double y1, double x2, double y2) {
			this.x1 = x1;
			this.y1 = y1;
			this.x2 = x2;
			this.y2 = y2;
		}
		public double lengthSquared() {
			return Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2);
		}
		public double length() {
			return Math.sqrt(lengthSquared());
		}
		public double angle() {
			return Math.toDegrees(Math.atan2(y2 - y1, x2 - x1));
		}
	}
	/**
	 * Finds all line segments in an image.
	 * @param input The image on which to perform the find lines.
	 * @param lineList The output where the lines are stored.
	 */
	private static void findLines(Mat input, ArrayList<Line> lineList) {
		final LineSegmentDetector lsd = Imgproc.createLineSegmentDetector();
		final Mat lines = new Mat();
		lineList.clear();
		if (input.channels() == 1) {
			lsd.detect(input, lines);
		} else {
			final Mat tmp = new Mat();
			Imgproc.cvtColor(input, tmp, Imgproc.COLOR_BGR2GRAY);
			lsd.detect(tmp, lines);
		}
		if (!lines.empty()) {
			for (int i = 0; i < lines.rows(); i++) {
				lineList.add(new Line(lines.get(i, 0)[0], lines.get(i, 0)[1],
					lines.get(i, 0)[2], lines.get(i, 0)[3]));
			}
		}
	}

	/**
	 * Filters out lines that do not meet certain criteria.
	 * @param inputs The lines that will be filtered.
	 * @param minLength The minimum length of a line to be kept.
	 * @param angle The minimum and maximum angle of a line to be kept.
	 * @param outputs The output lines after the filter.
	 */
	private static void filterLines(List<Line> inputs,double minLength,double[] angle,
		List<Line> outputs) {
			// TODO: we don't care about angle here
		outputs = inputs.stream()
				.filter(line -> line.lengthSquared() >= Math.pow(minLength,2))
				.filter(line -> (line.angle() >= angle[0] && line.angle() <= angle[1])
				|| (line.angle() + 180.0 >= angle[0] && line.angle() + 180.0 <= angle[1]))
				.collect(Collectors.toList());
	}

	/**
	 * Check if the lines describe a target, and if so return information on it
	 * @param lines
	 * @return null if no target found, else the target
	 */
	private static OuterPortTargetInImage findTarget(List<Line> lines) {
		OuterPortTargetInImage target = new OuterPortTargetInImage();

		if(lines.size() < 6) {
			// Takes at least 6 lines to describe an outer port target
			return null;
		}

		// Sort lines by length
		Collections.sort(lines, new Comparator<Line>() {
			@Override
			public int compare(Line arg0, Line arg1) {
				double ls0 = arg0.lengthSquared();
				double ls1 = arg1.lengthSquared();
				if(ls0 < ls1) {
					return -1;
				} else if(ls0 > ls1) {
					return 1;
				} else {
					return 0;
				}
			}
		});

		// Hypothesize that the longest 6 lines describe the target
		List<Line> targetLines = lines.subList(0, 6);

		// Find pairs of lines describing the three bars of reflective tape
		// Each of these pairs must be pretty close to parallel, or else this isn't the upper target.
		// If you can't find these pairs, say we have detected no target
		double horizontalMaxAngleDeg = 10;
		double horizontalMinAngleDeg = -10;
		List<Line> horizontals = targetLines.stream()
			.filter(line -> (line.angle() >= horizontalMinAngleDeg && line.angle() <= horizontalMaxAngleDeg))
			.collect(Collectors.toList());
		if(horizontals.size() != 2) {
			return null;
		}

		// Find the width of the target in pixels
		// -- > where should we measure from?  Furthest outer tips?  Would prefer not to be sensitive to brightness and blur level.
		// We could probably find the centerpoint of each "elbow", and measure the distance between those two.  That'd be insensitive to the above.

		return null;
	}

	private static OuterPortTargetRelRobot computeTargetLocation(OuterPortTargetInImage target) {
		// TODO
		// Will likely need some physical properties too, such as the field of view in each axis
		return null;
	}

	/**
	 * 
	 * @return
	 */
	public OuterPortTargetRelRobot getDetectedTarget() {
		return detectedTargetRelRobot;
	}

	public static void main(String[] args) {

		String[] filesToProcess = {
			"test_images/2020SampleVisionImages/BlueGoal-060in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-084in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-108in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-132in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-156in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-156in-Left.jpg                             ",
			"test_images/2020SampleVisionImages/BlueGoal-180in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-224in-Center.jpg                           ",
			"test_images/2020SampleVisionImages/BlueGoal-228in-ProtectedZone.jpg                    ",
			"test_images/2020SampleVisionImages/BlueGoal-330in-ProtectedZone.jpg                    ",
			"test_images/2020SampleVisionImages/BlueGoal-Far-ProtectedZone.jpg                      ",
			"test_images/2020SampleVisionImages/RedLoading-016in-Down.jpg                           ",
			"test_images/2020SampleVisionImages/RedLoading-030in-Down.jpg                           ",
			"test_images/2020SampleVisionImages/RedLoading-048in-Down.jpg                           ",
			"test_images/2020SampleVisionImages/RedLoading-048in.jpg                                 ",
			"test_images/2020SampleVisionImages/RedLoading-060in.jpg                                 ",
			"test_images/2020SampleVisionImages/RedLoading-084in.jpg                                 ",
			"test_images/2020SampleVisionImages/RedLoading-108in.jpg                                 ",
		};
	
		GripPipelineLinesFromTarget processor = new GripPipelineLinesFromTarget();
		for (String file : filesToProcess) {
			Mat img = Imgcodecs.imread(file);
			processor.process(img);


			HighGui.imshow(file, img);
		}
		HighGui.waitKey(10);
	}


}

